name: hylogen
version: 0.1.5.1
synopsis: GLSL embedded in Haskell
description: GLSL embedded in Haskell
homepage: https://github.com/sleexyz/hylogen
author: Sean Lee
license: MIT
maintainer: freshdried@gmail.com
category: Graphics
extra-source-files:
  - README.md

dependencies:
  - base >=4.8 && < 5
  - vector-space
  - data-reify

library:
  source-dirs: src
